name: Basic CI

run-name: CI to ${{github.workflow}} by ${{github.actor}}

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -B package -DskipTests
      - name: Upload jar Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-jar
          path: target/*.jar
      - name: Upload classes Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-classes
          path: target/classes/

  test:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: Run Tests
        run: mvn -B test
      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: target/surefire-reports/

  code-quality:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: Download classes Artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-classes
          path: target/classes/
      - name: Run SpotBugs
        run: mvn spotbugs:check
      - name: Upload SpotBugs Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: spotbugs-results
          path: target/spotbugsXml.xml
